# Generated by Django 3.1.4 on 2021-03-11 10:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playername', models.CharField(max_length=30)),
                ('highscore_arcade', models.PositiveIntegerField(default=0)),
                ('car', models.PositiveSmallIntegerField(default=0)),
                ('coins', models.PositiveIntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Leaderboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leaderboard_name', models.CharField(max_length=100)),
                ('nr_of_players', models.PositiveIntegerField(default=0)),
                ('highscores', models.ManyToManyField(to='leaderboard.Player')),
            ],
        ),
    ]
