# Generated by Django 3.1.4 on 2021-03-16 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Highscore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField()),
                ('player', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='leaderboard.player')),
            ],
        ),
        migrations.AlterField(
            model_name='leaderboard',
            name='highscores',
            field=models.ManyToManyField(to='leaderboard.Highscore'),
        ),
    ]
